import { toTitleCase } from "@utils/toTitle";
import Link from "next/link";

interface AutoGeneratedSumarryProps {
    content: string
}
interface TitleAnchorLink {
    href: string,
    name: string,
    type: number;
}


const symbolsToRemove = ["?", "/", "@", "+", ".", "!", "%", "$", "(", ")", "*", "<", ">", "&"];

const AutoGeneratedSumarry = ({ content }: AutoGeneratedSumarryProps) => {
    const titles: TitleAnchorLink[] = getPostTitles(content);

    if (titles.length == 0) return <></>;

    return (
        <div className="post-sumarry">
            <h2>Sumário</h2>
            <ul>
                {titles.map((anchor: TitleAnchorLink, index: number) => {
                    const link = <Link passHref href={"#" + anchor.href} replace>{toTitleCase(anchor.name)}</Link>
                    return anchor.type == 1 ?
                        <ul>
                            <li key={index}>
                                {link}
                            </li>
                        </ul>
                        :
                        <li key={index}>
                            {link}
                        </li>
                })}
            </ul>
        </div>
    );
}

const getPostTitles = (content: string): TitleAnchorLink[] => {
    const textLines = content.split('\n');
    const titles: TitleAnchorLink[] = [];
    textLines.map(((line: string) => {
        if (line.startsWith("# ")) {
            titles.push({ href: formatTitleLink(line), name: line.slice(2), type: 0 });
        } else if (line.startsWith("## ")) {
            titles.push({ href: formatTitleLink(line), name: line.slice(2), type: 1 });
        }
    }));
    return titles;
}


const formatTitleLink = (title: string): string => {
    let link = title.slice(2).toLowerCase().trim().split(" ").join("-");
    link = removeSymbolsFromLink(link);
    return link;
}

const removeSymbolsFromLink = (link: string): string => {
    symbolsToRemove.map((symbol: string) => {
        link = link.split(symbol).join("");
    });
    return link;
}

export default AutoGeneratedSumarry;