import Link from "next/link";

interface AutoGeneratedSumarryProps{
    content: string
}
interface TitleAnchorLink{
    href: string,
    name: string,
}

const AutoGeneratedSumarry = ({content}: AutoGeneratedSumarryProps) =>{   
    const titles = getPostTitles(content);
    const titleLinks: TitleAnchorLink[] = getTitleLinks(titles); 
    return(
        <>
        <div className="post-sumarry">
            <h3>Summary</h3>
            <ul>
                {titleLinks.map((anchor: TitleAnchorLink, index: number) => {
                    return (
                        <li key={index}>
                            <Link passHref href={"#" + anchor.href}>{anchor.name}</Link>
                        </li>
                    );
                })}
            </ul>
        </div></>
    );
}

const getPostTitles = (content: string)=>{
    const textLines = content.split('\n');
    const titles: string[] = [];
    textLines.map(((line: string) =>{
        if(line.startsWith("# ")){
            titles.push(line);
        }
    }));
    return titles;
}

const getTitleLinks = (titles: string[]): TitleAnchorLink[] =>{
    const titleLinks: TitleAnchorLink[] = [];
    titles.map((title: string) =>{
        let link = title.slice(2);
        // link = removeSymbolsFromLink(link);
        titleLinks.push({name: title.slice(2), href: link.toLowerCase().replaceAll(" ", "-")});
    });
    
    return titleLinks;
}

const removeSymbolsFromLink = (link: string): string =>{
    const symbolsToRemove = ["?", "/", "@", "+","."];
    symbolsToRemove.map((symbol: string) => {
        link = link.replaceAll(symbol,"");
    });
    
    return link;
}

export default AutoGeneratedSumarry;